name: defi_wallet
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #http
  http: ^0.13.3

  #crypto
  defichaindart:
    git:
      url: https://github.com/Jellywallet/DeFiChain-dart
      ref: 091cee22ee53716e8565f5f0871e83b9162bc705
  crypto: ^3.0.1

  #databases
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  shared_preferences: ^2.0.6

  #bloc
  flutter_bloc: ^8.0.1
  bloc: ^8.0.1

  #qr
  qr_flutter: ^4.0.0

  path_provider: ^2.0.2
  equatable: ^2.0.3

  dotted_border: ^2.0.0
  awesome_dropdown: ^0.0.4

  flutter_svg: ^0.22.0
  url_launcher: ^6.0.9

  cron: ^0.3.0

  fl_chart: ^0.36.2

  string_to_hex: ^0.2.2

  simple_tooltip: ^1.0.0

  custom_pop_up_menu: ^1.2.2

  basic_utils: ^3.6.0

  flutter_masked_text: ^0.8.0

  intl: ^0.17.0

  encrypt: ^5.0.1

  sentry_flutter: ^6.3.0

  percent_indicator: ^4.0.0

  email_validator: ^2.0.1
  mask_text_input_formatter: ^2.3.0
  intl_phone_field: ^3.1.0
  iban_form_field: ^0.2.2
  country_list_pick: ^1.0.1+6
  flutter_secure_storage: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.0.4
  hive_generator: ^1.1.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/tokens/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: IBM Plex Sans
      fonts:
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-Regular.ttf
          style: normal
    - family: IBM Plex Medium
      fonts:
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-Medium.ttf
          style: normal
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
